# Use a lightweight JRE base image
FROM eclipse-temurin:21-jre-alpine

ENV ZOO_HOME=/opt/zookeeper ZOO_DATA_DIR=/data ZOO_LOG_DIR=/logs PATH=$PATH:/opt/zookeeper/bin

# Install bash required by entrypoint and zkServer.sh
RUN apk add --no-cache bash

WORKDIR $ZOO_HOME

# Copy the local tarball generated by your Maven build
ARG TARBALL=zookeeper-assembly/target/apache-zookeeper-*-bin.tar.gz
COPY ${TARBALL} /tmp/zookeeper.tar.gz

# Extract contents and set up directories
RUN mkdir -p "$ZOO_HOME" "$ZOO_DATA_DIR" "$ZOO_LOG_DIR" && tar -xzf /tmp/zookeeper.tar.gz --strip-components=1 -C "$ZOO_HOME" && rm /tmp/zookeeper.tar.gz

# Add entrypoint script
COPY docker-entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

# Client, Follower, and Leader Election ports
EXPOSE 2181 2888 3888

ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["zkServer.sh", "start-foreground"]