version: "3.8"

services:
  zoo1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zoo1
    hostname: zoo1
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: "server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888"
    volumes:
      - zoo1_data:/data
      - zoo1_datalog:/logs

  zoo2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zoo2
    hostname: zoo2
    ports:
      - "2182:2181"
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: "server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888"
    volumes:
      - zoo2_data:/data
      - zoo2_datalog:/logs

  zoo3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zoo3
    hostname: zoo3
    ports:
      - "2183:2181"
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: "server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888"
    volumes:
      - zoo3_data:/data
      - zoo3_datalog:/logs

volumes:
  zoo1_data:
  zoo1_datalog:
  zoo2_data:
  zoo2_datalog:
  zoo3_data:
  zoo3_datalog:
